version: '3.7'

services:
    app:
        build: ${PWD}
        working_dir: /app
        links:
            - mysql
            - redis
        ports:
            - 9000:9000
        networks:
            - web

    mysql:
        image: mysql:latest
        volumes:
            - ${PWD}/.docker/db/billing:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: billing
        networks:
            - web

    redis:
        image: redis:alpine
        networks:
            - web

networks:
    web:
        external: true
